// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlWfXLzc_ur1c5Tsyqj5r6L1ZRBbBawx4',
    appId: '1:674553136591:web:812537863d5f5ce6d1feba',
    messagingSenderId: '674553136591',
    projectId: 'retail-solution-78f8f',
    authDomain: 'retail-solution-78f8f.firebaseapp.com',
    storageBucket: 'retail-solution-78f8f.firebasestorage.app',
    measurementId: 'G-L6YNWJTK13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVcPiAV_tFkfJtVzTrPsHlNBV62vrLELU',
    appId: '1:674553136591:android:309f39cd23bbaaf8d1feba',
    messagingSenderId: '674553136591',
    projectId: 'retail-solution-78f8f',
    storageBucket: 'retail-solution-78f8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNrc0aGb1KsgTWhTglq_G1iXPBthoN_IQ',
    appId: '1:674553136591:ios:c2ba0860817062eed1feba',
    messagingSenderId: '674553136591',
    projectId: 'retail-solution-78f8f',
    storageBucket: 'retail-solution-78f8f.firebasestorage.app',
    iosBundleId: 'com.hola.adaptive.countingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNrc0aGb1KsgTWhTglq_G1iXPBthoN_IQ',
    appId: '1:674553136591:ios:c2ba0860817062eed1feba',
    messagingSenderId: '674553136591',
    projectId: 'retail-solution-78f8f',
    storageBucket: 'retail-solution-78f8f.firebasestorage.app',
    iosBundleId: 'com.hola.adaptive.countingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlWfXLzc_ur1c5Tsyqj5r6L1ZRBbBawx4',
    appId: '1:674553136591:web:96f13b0a9861c387d1feba',
    messagingSenderId: '674553136591',
    projectId: 'retail-solution-78f8f',
    authDomain: 'retail-solution-78f8f.firebaseapp.com',
    storageBucket: 'retail-solution-78f8f.firebasestorage.app',
    measurementId: 'G-NN6PGYG8BD',
  );
}
